### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by richterjakob**

### CODE REVIEW

**Comment by ktbolt** [comment]
@richterjakob You must open a GitHub Issue for the changes you are making to the code, describe what the problem is and the modifications you are planning to make to fix it.

**Comment by richterjakob** [comment]
@ktbolt I was planning to do that as soon as the branch is ready, if that is okay. It is currently just a draft. I opened it to be able to compare all changes I made together to find the bug I introduced somewhere. I found it now and will bring the branch into a mergable state with a corresponding issue.

**Comment by richterjakob** [comment]
Corresponding to Issue https://github.com/SimVascular/svZeroDSolver/issues/62

**Comment by ktbolt** [comment]
@richterjakob I see the Issue, good!

**Pull request merged**
